FROM node:8.4.0
ENV NODE_ENV=test
RUN mkdir -p  /root/pizza-express
RUN apt-get install git && apt-get update && apt-get install -y vim
RUN git clone https://github.com/OrenAshkenazyBigID/pizza-express /root/pizza-express
WORKDIR /root/pizza-express
RUN npm cache clean --force
EXPOSE 6379
RUN apt-get install redis-server -y
RUN redis-server &
RUN npm install express
RUN npm install redis
RUN npm init & npm i express --save & npm i mocha --save-dev
CMD node server.js
