FROM node:8.4.0
ENV NODE_ENV=test
RUN mkdir -p  /root/pizza-express
RUN apt-get install git
RUN git clone https://github.com/OrenAshkenazyBigID/pizza-express /root/pizza-express
WORKDIR /pizza-express
RUN touch package.json & server.js
RUN npm install express & redis
RUN npm init & npm i express --save & npm i mocha --save-dev
CMD [ "node", "server.js" ]
